name: Backend CI Pipeline

on:
  pull_request:
    branches:
      - main
      - backend
  push:
    branches:
      - backend

jobs:
  backend-test:
    runs-on: ubuntu-latest
    if: {{ github.ref != 'refs/heads/frontend' }}
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3
  
      # Шаг 2: Установка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
  
      # Шаг 3: Кэширование Gradle зависимостей для ускорения сборки
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  
      # Шаг 4: Сделать gradlew исполняемым
      - name: Grant execute permission for gradlew
        run: chmod +x ./lnm-backend/gradlew
  
      # Шаг 5: Сборка проекта и запуск тестов
      - name: Run tests
        working-directory: ./lnm-backend
        run: ./gradlew test
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      # Шаг 6: Запуск тестов и проверка покрытия
      - name: Run tests and check coverage
        working-directory: ./lnm-backend
        run: ./gradlew check jacocoTestReport
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
  
      # Шаг 7: Публикация отчетов о тестах
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./lnm-backend/build/test-results/test
